framework:
    serializer:
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'
        enabled: true
        mapping:
            paths:
                - '%kernel.project_dir%/config/serializer'
        default_context:
            enable_max_depth: true