
services:
  app:
    image: php:8.2-fpm
    build:
      context: ./docker
      target: php
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - database
      - rabbitmq
      - elasticsearch
    ports:
      - "8080:8080"
    networks:
      - backbone

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data:rw
    networks:
      - backbone

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - backbone

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - backbone

volumes:
  database_data:
  elasticsearch_data:
  rabbitmq_data:
networks:
  backbone:
    driver: bridge